import { FIAT_METHOD, MODE, NETWORK, FIAT_CURRENCY, PRODUCT, CRYPTO_CURRENCY, THEME } from 'types/kado';

export const PAY_CURRENCIES_LIST = [FIAT_CURRENCY.USD];

export const REV_CURRENCIES_LIST = [CRYPTO_CURRENCY.IXO, CRYPTO_CURRENCY.USDC];

export const PRODUCTS_LIST = [PRODUCT.BUY];

export const NETWORKS_LIST = [NETWORK.IXO, NETWORK.NOBLE];

export const FIAT_METHODS_LIST = [FIAT_METHOD.CARD];

export const THEMES_LIST = [THEME.LIGHT, THEME.DARK];

export const MODES_LIST = [MODE.MINIMAL, MODE.FULL];
